"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 翻译字典
const translations = {
  zh: {
    // 通用
    'common.login': '登录',
    'common.logout': '退出',
    'common.submit': '提交',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.edit': '编辑',
    'common.delete': '删除',
    'common.add': '添加',
    'common.create': '创建',
    'common.update': '更新',
    'common.save': '保存',
    'common.back': '返回',
    'common.refresh': '刷新',
    'common.loading': '加载中...',
    'common.yes': '是',
    'common.no': '否',
    'common.online': '在线',
    'common.offline': '离线',
    'common.unauthorized': 'IP不匹配',
    'common.status': '状态',
    'common.name': '名称',
    'common.description': '描述',
    'common.actions': '操作',
    'common.createdAt': '创建时间',
    'common.lastUpdated': '最后更新',
    
    // 首页
    'home.title': 'SimpleMES',
    'home.subtitle': '选择您的访问方式',
    'home.adminPortal': '管理后台',
    'home.clientPortal': '客户端',
    
    // 登录页面
    'login.adminTitle': '管理员登录',
    'login.clientTitle': '客户端登录',
    'login.username': '用户名',
    'login.password': '密码',
    'login.loginButton': '登录',
    'login.loggingIn': '登录中...',
    'login.backToHome': '返回首页',
    'login.defaultAccount': '默认账户',
    'login.selectLanguage': '选择语言',
    'login.language.zh': '中文',
    'login.language.en': 'English',
    'login.credentials.admin': 'admin / admin',
    'login.credentials.client': 'client / client',
    'login.enterCredentials': '请输入您的管理员凭据',
    'login.enterClientCredentials': '请输入您的客户端凭据',
    
    // 客户端选择
    'clientSelect.title': '选择客户端',
    'clientSelect.subtitle': '您的IP地址与配置不匹配，请选择要登录的客户端',
    'clientSelect.currentIp': '当前IP',
    'clientSelect.configuredIp': '配置IP',
    'clientSelect.confirmLogin': '确认登录',
    'clientSelect.backToLogin': '返回登录',
    'clientSelect.pleaseSelect': '请选择一个工位',
    
    // 智能匹配工位
    'smartMatching.title': '智能匹配成功！',
    'smartMatching.detectingIp': '检测到您的IP地址',
    'smartMatching.autoLoginWorkstation': '自动登录工位',
    'smartMatching.loginProgress': '登录中...',
    
    // 仪表盘
    'dashboard.admin.title': '管理控制台',
    'dashboard.client.title': '客户端控制台',
    'dashboard.welcome': '欢迎',
    'dashboard.currentTasks': '当前任务',
    'dashboard.completed': '已完成',
    'dashboard.runtime': '运行时间',
    'dashboard.taskList': '任务列表',
    'dashboard.systemInfo': '系统信息',
    'dashboard.version': '版本',
    'dashboard.lastUpdate': '最后更新',
    'dashboard.loginUser': '登录用户',
    'dashboard.configSync': '配置同步',
    'dashboard.configSynced': '配置已同步',
    'dashboard.configSyncIpIssue': '配置同步 (IP异常)',
    'dashboard.configDescription': '所有配置参数已从管理端同步到本地',
    'dashboard.configIpMismatch': 'IP地址不匹配，请联系管理员确认网络配置',
    'dashboard.manualSync': '手动同步',
    
    // 网络连接信息
    'network.title': '网络连接信息',
    'network.currentIp': '当前IP地址',
    'network.configuredIp': '配置IP地址',
    'network.statusOnline': '在线 (IP匹配)',
    'network.statusUnauthorized': '在线 (IP不匹配)',
    'network.statusOffline': '离线',
    'network.ipMismatchWarning': '⚠️ 当前IP地址与配置的IP地址不匹配，系统已记录此次访问。',
    
    // 管理页面
    'admin.users.title': '用户管理',
    'admin.users.subtitle': '系统用户账户管理',
    'admin.users.addUser': '添加用户',
    'admin.users.editUser': '编辑用户',
    'admin.users.email': '邮箱',
    'admin.users.role': '角色',
    'admin.users.deleteConfirm': '确定要删除用户',
    
    'admin.roles.title': '角色权限管理',
    'admin.roles.subtitle': '管理系统角色和权限分配，支持RBAC权限控制',
    'admin.roles.addRole': '添加角色',
    'admin.roles.editRole': '编辑角色',
    'admin.roles.roleName': '角色名称',
    'admin.roles.roleDescription': '角色描述',
    'admin.roles.permissions': '权限分配',
    'admin.roles.userCount': '用户数量',
    'admin.roles.permissionCount': '权限数量',
    'admin.roles.deleteConfirm': '确定要删除角色',
    
    'admin.clients.title': '客户端配置',
    'admin.clients.subtitle': '管理客户端配置和IP地址验证',
    'admin.clients.addClient': '添加客户端',
    'admin.clients.editClient': '编辑客户端',
    'admin.clients.clientId': '客户端ID',
    'admin.clients.clientName': '客户端名称',
    'admin.clients.configuredIp': '配置IP地址',
    'admin.clients.currentIp': '当前IP',
    'admin.clients.lastConnected': '最后连接',
    'admin.clients.timeout': '超时时间 (毫秒)',
    'admin.clients.retryCount': '重试次数',
    'admin.clients.autoConnect': '自动连接',
    'admin.clients.deleteConfirm': '确定要删除客户端',
    
    'admin.devices.title': '设备管理',
    'admin.devices.subtitle': '管理各客户端的设备配置和状态监控',
    'admin.devices.addDevice': '添加设备',
    'admin.devices.editDevice': '编辑设备',
    'admin.devices.deviceId': '设备ID',
    'admin.devices.deviceName': '设备名称',
    'admin.devices.deviceType': '设备类型',
    'admin.devices.brand': '品牌',
    'admin.devices.model': '型号',
    'admin.devices.description': '设备描述',
    'admin.devices.client': '所属客户端',
    'admin.devices.ipAddress': 'IP地址',
    'admin.devices.port': '端口号',
    'admin.devices.protocol': '通信协议',
    'admin.devices.connectionString': '连接字符串',
    'admin.devices.status': '设备状态',
    'admin.devices.lastConnected': '最后连接',
    'admin.devices.lastHeartbeat': '最后心跳',
    'admin.devices.deleteConfirm': '确定要删除设备',
    'admin.devices.plcController': 'PLC控制器',
    'admin.devices.screwdriver': '螺丝刀控制器',
    'admin.devices.barcodeScanner': '扫码枪',
    'admin.devices.sensor': '传感器',
    'admin.devices.camera': '摄像头',
    'admin.devices.printer': '打印机',
    'admin.devices.robot': '机器人',
    'admin.devices.other': '其他设备',
    'admin.devices.statusOnline': '在线',
    'admin.devices.statusOffline': '离线',
    'admin.devices.statusError': '错误',
    'admin.devices.statusMaintenance': '维护中',
    
    // 工位管理
    'admin.workstations.title': '工位管理',
    'admin.workstations.subtitle': '工位配置与设备分配管理',
    'admin.workstations.workstationList': '工位列表',
    'admin.workstations.workstationId': '工位ID',
    'admin.workstations.workstationName': '工位名称',
    'admin.workstations.configuredIp': '配置IP',
    'admin.workstations.deviceCount': '设备数量',
    'admin.workstations.addWorkstation': '添加新工位',
    'admin.workstations.editWorkstation': '编辑工位',
    'admin.workstations.workstationInfo': '工位信息',
    'admin.workstations.workstationDevices': '工位设备',
    'admin.workstations.addDeviceToWorkstation': '添加设备到工位',
    'admin.workstations.deviceManagement': '设备管理',
    'admin.workstations.location': '位置',
    'admin.workstations.configuredIpAddress': '配置IP地址',
    'admin.workstations.editDevice': '编辑设备',
    'admin.workstations.removeDevice': '移除设备',
    'admin.workstations.noDevices': '暂无设备',
    'admin.workstations.deviceDetails': '设备详情',
    'admin.workstations.selectDeviceType': '选择设备类型',
    'admin.workstations.allTypes': '所有类型',
    'admin.workstations.addSelectedDevices': '添加选中设备',
    'admin.workstations.removeConfirm': '确定要从工位移除此设备吗？',
    'admin.workstations.deleteConfirm': '确定要删除此设备吗？',
    'admin.workstations.deleteWorkstationConfirm': '确定要删除工位吗？',
    'admin.workstations.saveSuccess': '保存成功',
    'admin.workstations.saveFailed': '保存失败',
    'admin.workstations.addDeviceFailed': '添加设备失败',
    'admin.workstations.removeDeviceFailed': '移除设备失败',
    'admin.workstations.deleteDeviceFailed': '删除设备失败',
    'admin.workstations.updateDeviceFailed': '更新设备失败',
    'admin.workstations.tab.info': '基本信息',
    'admin.workstations.tab.devices': '设备管理',
    
    // 菜单翻译
    'menu.dashboard': '仪表盘',
    'menu.users': '用户管理',
    'menu.clients': '客户端配置',
    'menu.devices': '设备管理',
    'menu.workstations': '工位管理',
    'menu.roles': '角色权限',
    'menu.settings': '系统设置',
    'menu.profile': '个人资料',
    'menu.avatar': '更换头像',
    'menu.account': '账户设置',
    'menu.logout': '退出登录',
    'menu.welcome': '欢迎回来',
    'menu.admin': '管理员',
    'menu.supervisor': '班长',
    'menu.engineer': '工程师',
    'menu.operator': '普通员工',
    'menu.systemAdmin': '系统管理员',
    'menu.adminPortal': 'SimpleMES 管理',
    'menu.adminSubtitle': '管理后台',
    'error.networkError': '网络错误，请重试',
    'error.loginFailed': '登录失败',
    'error.invalidCredentials': '用户名或密码错误',
    'error.noPermission': '无权限访问',
    'error.serverError': '服务器内部错误',
    'error.operationFailed': '操作失败',
    'error.deleteFailed': '删除失败',
    
    // Profile相关
    'profile.currentPassword': '当前密码',
    'profile.newPassword': '新密码',
    'profile.confirmPassword': '确认密码',
    'profile.changePassword': '修改密码',
    'profile.passwordChanged': '密码修改成功',
    'profile.passwordChangeFailed': '密码修改失败',
    'profile.passwordMismatch': '密码确认不匹配',
    'profile.selectImage': '选择头像图片',
    'profile.avatarUpdated': '头像更新成功',
    'profile.avatarUpdateFailed': '头像更新失败',
    'common.saveSuccess': '保存成功',
    'common.saveFailed': '保存失败',
    
    // 工艺管理
    'processes.steps.addStepsTitle': '添加工艺步骤',
    'processes.steps.selectedStepIds': '选中步骤ID',
    'processes.steps.selectedStepIdsPlaceholder': '选中的步骤ID将显示在此处...',
    'processes.steps.searchPlaceholder': '按名称或ID搜索...',
    'processes.steps.allCategories': '所有分类',
    'processes.steps.stepId': '步骤ID',
    'processes.steps.stepName': '步骤名称',
    'processes.steps.description': '描述',
    'processes.steps.workstation': '工位类型',
    'processes.steps.stepType': '步骤类型',
    'processes.steps.universal': '通用',
    'processes.steps.noMatchingSteps': '未找到匹配的步骤模板',
    'processes.steps.addNewStep': '添加新工艺步骤',
    'processes.steps.saveOrder': '保存顺序',
    'processes.steps.columns': '列管理',
    'processes.steps.order': '顺序',
    'processes.steps.name': '名称',
    'processes.steps.stationType': '工位类型',
    'processes.steps.processStepId': '工艺步骤ID',
    
    // 工位选择
    'workstationSelect.title': '请选择工位',
    'workstationSelect.chooseStation': '选择工位...',
    'workstationSelect.select': '选择',
    'workstationSelect.cancel': '取消',
    'workstationSelect.connecting': '连接中...',
    'workstationSelect.connectionSuccessful': '连接成功！',
    'workstationSelect.connectionFailed': '连接失败',
    'workstationSelect.connectedTo': '已连接到',
    'workstationSelect.enteringWorkstation': '进入工位...',
    'workstationSelect.detectedIp': '检测到IP',
    'workstationSelect.noMatchingStation': '未找到匹配的工位',
    'workstationSelect.noStationsAvailable': '暂无可用工位',
    'workstationSelect.contactAdmin': '请联系管理员',
    
    // 工位操作界面
    'workstation.start': '开始',
    'workstation.startProcessing': '启动中...',
    'workstation.adjustSequence': '调整序列',
    'workstation.manualInsert': '手动插入',
    'workstation.menu': '菜单',
    'workstation.logout': '退出登录',
    'workstation.serviceMode': '服务模式',
    'workstation.selectedOrder': '当前选中订单',
    'workstation.orderNumber': '订单号',
    'workstation.carNumber': '车号',
    'workstation.productFamily': '产品族',
    'workstation.carrierId': '载具ID',
    'workstation.pleaseSelectOrder': '请先选择一个订单',
    'workstation.orderStarted': '订单开始生产',
    'workstation.startProcessingFailed': '启动生产失败',
    'workstation.adjustSequenceFunction': '调整序列功能 - 开发中',
    'workstation.manualInsertFunction': '手动插入功能 - 开发中',
    'workstation.serviceModeFunction': '服务模式功能 - 开发中',
    
    // 手动插入订单
    'manualInsert.title': '手动插入订单',
    'manualInsert.inputLabel': '请输入生产号（车号）',
    'manualInsert.placeholder': '例如：T001',
    'manualInsert.description': '输入订单的生产号，系统将查找并打开对应的订单',
    'manualInsert.cancel': '取消',
    'manualInsert.submit': '确定',
    'manualInsert.searching': '查询中...',
    'manualInsert.pleaseEnter': '请输入生产号',
    'manualInsert.orderNotFound': '未找到对应的订单，请检查生产号是否正确',
    'manualInsert.invalidStatus': '订单状态为 {status}，无法执行。只能执行待开始或进行中的订单。',
    'manualInsert.searchFailed': '查询订单失败',
    
    // 服务模式界面
    'serviceMode.title': '工位配置的设备:',
    'serviceMode.deviceName': '设备名称',
    'serviceMode.deviceType': '设备类型',
    'serviceMode.test': '测试',
    'serviceMode.testing': '测试中...',
    'serviceMode.testSuccess': '连接成功',
    'serviceMode.testFailed': '连接失败',
    'serviceMode.backToWorkstation': '返回工位',
    'serviceMode.noDevices': '该工位未配置设备',
    'serviceMode.loadingDevices': '加载设备中...',
  },
  en: {
    // Common
    'common.login': 'Login',
    'common.logout': 'Logout',
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.save': 'Save',
    'common.back': 'Back',
    'common.refresh': 'Refresh',
    'common.loading': 'Loading...',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.online': 'Online',
    'common.offline': 'Offline',
    'common.unauthorized': 'IP Mismatch',
    'common.status': 'Status',
    'common.name': 'Name',
    'common.description': 'Description',
    'common.actions': 'Actions',
    'common.createdAt': 'Created At',
    'common.lastUpdated': 'Last Updated',
    
    // Home
    'home.title': 'SimpleMES',
    'home.subtitle': 'Choose your access method',
    'home.adminPortal': 'Admin Portal',
    'home.clientPortal': 'Client Portal',
    
    // Login
    'login.adminTitle': 'Admin Login',
    'login.clientTitle': 'Client Login',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.loginButton': 'Login',
    'login.loggingIn': 'Logging in...',
    'login.backToHome': 'Back to Home',
    'login.defaultAccount': 'Default Account',
    'login.selectLanguage': 'Select Language',
    'login.language.zh': '中文',
    'login.language.en': 'English',
    'login.credentials.admin': 'admin / admin',
    'login.credentials.client': 'client / client',
    'login.enterCredentials': 'Please enter your admin credentials',
    'login.enterClientCredentials': 'Please enter your client credentials',
    
    // Client Selection
    'clientSelect.title': 'Select Client',
    'clientSelect.subtitle': 'Your IP address does not match the configuration, please select a client to login',
    'clientSelect.currentIp': 'Current IP',
    'clientSelect.configuredIp': 'Configured IP',
    'clientSelect.confirmLogin': 'Confirm Login',
    'clientSelect.backToLogin': 'Back to Login',
    'clientSelect.pleaseSelect': 'Please select a workstation',
    
    // Smart Matching
    'smartMatching.title': 'Smart matching successful!',
    'smartMatching.detectingIp': 'Detected your IP address',
    'smartMatching.autoLoginWorkstation': 'Auto login workstation',
    'smartMatching.loginProgress': 'Logging in...',
    
    // Dashboard
    'dashboard.admin.title': 'Admin Console',
    'dashboard.client.title': 'Client Console',
    'dashboard.welcome': 'Welcome',
    'dashboard.currentTasks': 'Current Tasks',
    'dashboard.completed': 'Completed',
    'dashboard.runtime': 'Runtime',
    'dashboard.taskList': 'Task List',
    'dashboard.systemInfo': 'System Info',
    'dashboard.version': 'Version',
    'dashboard.lastUpdate': 'Last Update',
    'dashboard.loginUser': 'Login User',
    'dashboard.configSync': 'Config Sync',
    'dashboard.configSynced': 'Config Synced',
    'dashboard.configSyncIpIssue': 'Config Sync (IP Issue)',
    'dashboard.configDescription': 'All configuration parameters have been synced from admin to local',
    'dashboard.configIpMismatch': 'IP address mismatch, please contact administrator to confirm network configuration',
    'dashboard.manualSync': 'Manual Sync',
    
    // Network Info
    'network.title': 'Network Connection Info',
    'network.currentIp': 'Current IP Address',
    'network.configuredIp': 'Configured IP Address',
    'network.statusOnline': 'Online (IP Match)',
    'network.statusUnauthorized': 'Online (IP Mismatch)',
    'network.statusOffline': 'Offline',
    'network.ipMismatchWarning': '⚠️ Current IP address does not match configured IP address, this access has been logged.',
    
    // Admin Pages
    'admin.users.title': 'User Management',
    'admin.users.subtitle': 'System user account management',
    'admin.users.addUser': 'Add User',
    'admin.users.editUser': 'Edit User',
    'admin.users.email': 'Email',
    'admin.users.role': 'Role',
    'admin.users.deleteConfirm': 'Are you sure you want to delete user',
    
    'admin.roles.title': 'Role Permission Management',
    'admin.roles.subtitle': 'Manage system roles and permission assignments, supports RBAC permission control',
    'admin.roles.addRole': 'Add Role',
    'admin.roles.editRole': 'Edit Role',
    'admin.roles.roleName': 'Role Name',
    'admin.roles.roleDescription': 'Role Description',
    'admin.roles.permissions': 'Permission Assignment',
    'admin.roles.userCount': 'User Count',
    'admin.roles.permissionCount': 'Permission Count',
    'admin.roles.deleteConfirm': 'Are you sure you want to delete role',
    
    'admin.clients.title': 'Client Configuration',
    'admin.clients.subtitle': 'Manage client configuration and IP address verification',
    'admin.clients.addClient': 'Add Client',
    'admin.clients.editClient': 'Edit Client',
    'admin.clients.clientId': 'Client ID',
    'admin.clients.clientName': 'Client Name',
    'admin.clients.configuredIp': 'Configured IP Address',
    'admin.clients.currentIp': 'Current IP',
    'admin.clients.lastConnected': 'Last Connected',
    'admin.clients.timeout': 'Timeout (ms)',
    'admin.clients.retryCount': 'Retry Count',
    'admin.clients.autoConnect': 'Auto Connect',
    'admin.clients.deleteConfirm': 'Are you sure you want to delete client',
    
    'admin.devices.title': 'Device Management',
    'admin.devices.subtitle': 'Manage device configuration and status monitoring for each client',
    'admin.devices.addDevice': 'Add Device',
    'admin.devices.editDevice': 'Edit Device',
    'admin.devices.deviceId': 'Device ID',
    'admin.devices.deviceName': 'Device Name',
    'admin.devices.deviceType': 'Device Type',
    'admin.devices.brand': 'Brand',
    'admin.devices.model': 'Model',
    'admin.devices.description': 'Description',
    'admin.devices.client': 'Client',
    'admin.devices.ipAddress': 'IP Address',
    'admin.devices.port': 'Port',
    'admin.devices.protocol': 'Protocol',
    'admin.devices.connectionString': 'Connection String',
    'admin.devices.status': 'Status',
    'admin.devices.lastConnected': 'Last Connected',
    'admin.devices.lastHeartbeat': 'Last Heartbeat',
    'admin.devices.deleteConfirm': 'Are you sure you want to delete device',
    'admin.devices.plcController': 'PLC Controller',
    'admin.devices.screwdriver': 'Screwdriver Controller',
    'admin.devices.barcodeScanner': 'Barcode Scanner',
    'admin.devices.sensor': 'Sensor',
    'admin.devices.camera': 'Camera',
    'admin.devices.printer': 'Printer',
    'admin.devices.robot': 'Robot',
    'admin.devices.other': 'Other Device',
    'admin.devices.statusOnline': 'Online',
    'admin.devices.statusOffline': 'Offline',
    'admin.devices.statusError': 'Error',
    'admin.devices.statusMaintenance': 'Maintenance',
    
    // Workstation Management
    'admin.workstations.title': 'Workstation Management',
    'admin.workstations.subtitle': 'Workstation configuration and device assignment management',
    'admin.workstations.workstationList': 'Workstation List',
    'admin.workstations.workstationId': 'Workstation ID',
    'admin.workstations.workstationName': 'Workstation Name',
    'admin.workstations.configuredIp': 'Configured IP',
    'admin.workstations.deviceCount': 'Device Count',
    'admin.workstations.addWorkstation': 'Add New Workstation',
    'admin.workstations.editWorkstation': 'Edit Workstation',
    'admin.workstations.workstationInfo': 'Workstation Info',
    'admin.workstations.workstationDevices': 'Workstation Devices',
    'admin.workstations.addDeviceToWorkstation': 'Add Device to Workstation',
    'admin.workstations.deviceManagement': 'Device Management',
    'admin.workstations.location': 'Location',
    'admin.workstations.configuredIpAddress': 'Configured IP Address',
    'admin.workstations.editDevice': 'Edit Device',
    'admin.workstations.removeDevice': 'Remove Device',
    'admin.workstations.noDevices': 'No devices',
    'admin.workstations.deviceDetails': 'Device Details',
    'admin.workstations.selectDeviceType': 'Select Device Type',
    'admin.workstations.allTypes': 'All Types',
    'admin.workstations.addSelectedDevices': 'Add Selected Devices',
    'admin.workstations.removeConfirm': 'Are you sure you want to remove this device from the workstation?',
    'admin.workstations.deleteConfirm': 'Are you sure you want to delete this device?',
    'admin.workstations.deleteWorkstationConfirm': 'Are you sure you want to delete this workstation?',
    'admin.workstations.saveSuccess': 'Saved successfully',
    'admin.workstations.saveFailed': 'Save failed',
    'admin.workstations.addDeviceFailed': 'Failed to add device',
    'admin.workstations.removeDeviceFailed': 'Failed to remove device',
    'admin.workstations.deleteDeviceFailed': 'Failed to delete device',
    'admin.workstations.updateDeviceFailed': 'Failed to update device',
    'admin.workstations.tab.info': 'Basic Info',
    'admin.workstations.tab.devices': 'Device Management',
    
    // Menu translations
    'menu.dashboard': 'Dashboard',
    'menu.users': 'User Management',
    'menu.clients': 'Client Configuration',
    'menu.devices': 'Device Management',
    'menu.workstations': 'Workstation Management',
    'menu.roles': 'Role Management',
    'menu.settings': 'System Settings',
    'menu.profile': 'Profile',
    'menu.avatar': 'Change Avatar',
    'menu.account': 'Account Settings',
    'menu.logout': 'Logout',
    'menu.welcome': 'Welcome back',
    'menu.admin': 'Admin',
    'menu.supervisor': 'Supervisor',
    'menu.engineer': 'Engineer',
    'menu.operator': 'Operator',
    'menu.systemAdmin': 'System Administrator',
    'menu.adminPortal': 'SimpleMES Admin',
    'menu.adminSubtitle': 'Admin Portal',
    
    // Error Messages
    'error.networkError': 'Network error, please try again',
    'error.loginFailed': 'Login failed',
    'error.invalidCredentials': 'Invalid username or password',
    'error.noPermission': 'No permission to access',
    'error.serverError': 'Internal server error',
    'error.operationFailed': 'Operation failed',
    'error.deleteFailed': 'Delete failed',
    
    // Profile related
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.confirmPassword': 'Confirm Password',
    'profile.changePassword': 'Change Password',
    'profile.passwordChanged': 'Password changed successfully',
    'profile.passwordChangeFailed': 'Failed to change password',
    'profile.passwordMismatch': 'Password confirmation does not match',
    'profile.selectImage': 'Select avatar image',
    'profile.avatarUpdated': 'Avatar updated successfully',
    'profile.avatarUpdateFailed': 'Failed to update avatar',
    'common.saveSuccess': 'Saved successfully',
    'common.saveFailed': 'Save failed',
    
    // Process Management
    'processes.steps.addStepsTitle': 'Add Process Steps',
    'processes.steps.selectedStepIds': 'Selected Step IDs',
    'processes.steps.selectedStepIdsPlaceholder': 'Selected step IDs will appear here...',
    'processes.steps.searchPlaceholder': 'Search by name or ID...',
    'processes.steps.allCategories': 'All Categories',
    'processes.steps.stepId': 'Step ID',
    'processes.steps.stepName': 'Step Name',
    'processes.steps.description': 'Description',
    'processes.steps.workstation': 'Station Type',
    'processes.steps.stepType': 'Step Type',
    'processes.steps.universal': 'Universal',
    'processes.steps.noMatchingSteps': 'No matching step templates found',
    'processes.steps.addNewStep': 'Add new process step',
    'processes.steps.saveOrder': 'Save order',
    'processes.steps.columns': 'Columns',
    'processes.steps.order': 'Order',
    'processes.steps.name': 'Name',
    'processes.steps.stationType': 'Station type',
    'processes.steps.processStepId': 'Process step ID',
    
    // Workstation Selection
    'workstationSelect.title': 'Please select the station',
    'workstationSelect.chooseStation': 'Choose station...',
    'workstationSelect.select': 'SELECT',
    'workstationSelect.cancel': 'CANCEL',
    'workstationSelect.connecting': 'Connecting...',
    'workstationSelect.connectionSuccessful': 'Connection Successful!',
    'workstationSelect.connectionFailed': 'Connection Failed',
    'workstationSelect.connectedTo': 'Connected to',
    'workstationSelect.enteringWorkstation': 'Entering workstation...',
    'workstationSelect.detectedIp': 'Detected IP',
    'workstationSelect.noMatchingStation': 'No matching station found for this IP',
    'workstationSelect.noStationsAvailable': 'No stations available',
    'workstationSelect.contactAdmin': 'Please contact administrator',
    
    // Workstation Operation Interface
    'workstation.start': 'START',
    'workstation.startProcessing': 'Starting...',
    'workstation.adjustSequence': 'ADJUST SEQUENCE',
    'workstation.manualInsert': 'MANUAL INSERT',
    'workstation.menu': 'MENU',
    'workstation.logout': 'LOGOUT',
    'workstation.serviceMode': 'SERVICE MODE',
    'workstation.selectedOrder': 'Selected Order',
    'workstation.orderNumber': 'Order Number',
    'workstation.carNumber': 'Car Number',
    'workstation.productFamily': 'Product Family',
    'workstation.carrierId': 'Carrier ID',
    'workstation.pleaseSelectOrder': 'Please select an order first',
    'workstation.orderStarted': 'Order started production',
    'workstation.startProcessingFailed': 'Failed to start production',
    'workstation.adjustSequenceFunction': 'Adjust sequence function - In development',
    'workstation.manualInsertFunction': 'Manual insert function - In development',
    'workstation.serviceModeFunction': 'Service mode function - In development',
    
    // Manual Insert Order
    'manualInsert.title': 'Manual Insert Order',
    'manualInsert.inputLabel': 'Please enter production number',
    'manualInsert.placeholder': 'e.g., T001',
    'manualInsert.description': 'Enter the production number to search and open the corresponding order',
    'manualInsert.cancel': 'Cancel',
    'manualInsert.submit': 'Submit',
    'manualInsert.searching': 'Searching...',
    'manualInsert.pleaseEnter': 'Please enter production number',
    'manualInsert.orderNotFound': 'Order not found, please check if production number is correct',
    'manualInsert.invalidStatus': 'Order status is {status}, cannot execute. Only pending or in-progress orders can be executed.',
    'manualInsert.searchFailed': 'Failed to search order',
    
    // Service Mode Interface
    'serviceMode.title': 'Devices configured for the station:',
    'serviceMode.deviceName': 'Device name',
    'serviceMode.deviceType': 'Device type',
    'serviceMode.test': 'TEST',
    'serviceMode.testing': 'Testing...',
    'serviceMode.testSuccess': 'Connection successful',
    'serviceMode.testFailed': 'Connection failed',
    'serviceMode.backToWorkstation': 'Back to workstation',
    'serviceMode.noDevices': 'No devices configured for this workstation',
    'serviceMode.loadingDevices': 'Loading devices...',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('zh');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'zh' || savedLanguage === 'en')) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[Language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}